### ISSUE TITLE
Update ouroboros-consensus to build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-consensus#122] opened 2023-05-30 22:54 UTC
[ ] - Make it build
[ ] - Add to CI
[ ] - Upload to Hackage

**Comment by amesgen** [comment] 2023-05-31 08:24
Seems like a duplicate of #66, can we close one of these?

**Comment by amesgen** [comment] 2023-07-19 08:05
#66 was closed

**Closed by amesgen** 2023-07-19 08:05 UTC
